### ISSUE TITLE
运行docker-compose.yml报错

### ISSUE THREAD

**Issue by 897896639** [haxqer/confluence#29]
镜像confluence-srv 无法启动，8.5.1，8.5.0，8.5.1-zh都试过，无法启动。报错信息如下，
16-Sep-2023 11:21:02.399 INFO [Catalina-utility-2] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
16-Sep-2023 11:21:02.428 INFO [Catalina-utility-2] org.apache.catalina.core.ApplicationContext.log 1 Spring WebApplicationInitializers detected on classpath
16-Sep-2023 11:21:02.561 INFO [Catalina-utility-2] org.apache.catalina.core.ApplicationContext.log Initializing Spring DispatcherServlet 'dispatcher'
16-Sep-2023 11:21:03.233 SEVERE [main] org.apache.catalina.core.ContainerBase.startInternal A child container failed during start
        java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: A child container failed during start
                at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
                at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:873)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:249)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:923)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
        Caused by: org.apache.catalina.LifecycleException: A child container failed during start
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:885)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:795)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1328)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1318)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
                ... 13 more
        Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@364a830d]
                at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
                at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:873)
                ... 21 more
        Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@364a830d]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:139)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
                at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:725)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4607)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4740)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1328)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1318)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:829)
        Caused by: java.lang.IllegalArgumentException: java.io.IOException: java.lang.reflect.InvocationTargetException
                at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:141)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                ... 14 more
        Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
                at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:209)
                at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:257)
                at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:138)
                ... 15 more
        Caused by: java.lang.reflect.InvocationTargetException
                at java.base/jdk.internal.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:206)
                ... 17 more
        Caused by: java.util.zip.ZipException: zip END header not found
                at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
                at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
                at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
                at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
                at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
                at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
                at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
                at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
                at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
                at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
                ... 21 more
16-Sep-2023 11:21:03.234 SEVERE [main] org.apache.catalina.startup.Catalina.start The required Server component failed to start so Tomcat is unable to start.
        org.apache.catalina.LifecycleException: A child container failed during start
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:885)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:249)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:923)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
        Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: A child container failed during start
                at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
                at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:873)
                ... 13 more
        Caused by: org.apache.catalina.LifecycleException: A child container failed during start
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:885)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:795)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1328)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1318)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
                ... 13 more
        Caused by: java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@364a830d]
                at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
                at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:873)
                ... 21 more
        Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@364a830d]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:139)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
                at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:725)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4607)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4740)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1328)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1318)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:829)
        Caused by: java.lang.IllegalArgumentException: java.io.IOException: java.lang.reflect.InvocationTargetException
                at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:141)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                ... 14 more
        Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
                at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:209)
                at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:257)
                at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:138)
                ... 15 more
        Caused by: java.lang.reflect.InvocationTargetException
                at java.base/jdk.internal.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:206)
                ... 17 more
        Caused by: java.util.zip.ZipException: zip END header not found
                at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
                at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
                at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
                at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
                at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
                at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
                at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
                at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
                at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
                at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
                ... 21 more
16-Sep-2023 11:21:03.235 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8090"]
16-Sep-2023 11:21:03.235 INFO [main] org.apache.catalina.core.StandardService.stopInternal Stopping service [Tomcat-Standalone]
16-Sep-2023 11:21:03.236 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8090"]
16-Sep-2023 11:21:03.236 SEVERE [main] org.apache.catalina.util.LifecycleBase.destroy Called stop() on failed component [StandardEngine[Standalone].StandardHost[localhost]] to trigger clean-up but it failed too
        org.apache.catalina.LifecycleException: Failed to stop component [StandardEngine[Standalone].StandardHost[localhost]]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
                at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:267)
                at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:293)
                at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:778)
                at org.apache.catalina.core.ContainerBase.destroyInternal(ContainerBase.java:983)
                at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:321)
                at org.apache.catalina.core.StandardService.destroyInternal(StandardService.java:572)
                at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:321)
                at org.apache.catalina.core.StandardServer.destroyInternal(StandardServer.java:1049)
                at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:321)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:776)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
        Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@266374ef[Not completed, task = org.apache.catalina.core.ContainerBase$StopChild@5d99c6b5] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@13b3d178[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 2]
                at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
                at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:579)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:731)
                at org.apache.tomcat.util.threads.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:74)
                at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:931)
                at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
                ... 15 more
16-Sep-2023 11:21:03.242 INFO [main] org.apache.catalina.core.ApplicationContext.log Destroying Spring FrameworkServlet 'dispatcher'
executing as current user
If you encounter issues starting up Confluence, please see the Installation guide at http://confluence.atlassian.com/display/DOC/Confluence+Installation+Guide

Server startup logs are located in /opt/confluence/logs/catalina.out
---------------------------------------------------------------------------
Using Java: /usr/local/openjdk-11/bin/java
2023-09-16 11:21:05,188 INFO [main] [atlassian.confluence.bootstrap.SynchronyProxyWatchdog] A Context element for ${confluence.context.path}/synchrony-proxy is found in /opt/confluence/conf/server.xml. No further action is required
---------------------------------------------------------------------------
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
16-Sep-2023 11:21:05.866 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8090"]
16-Sep-2023 11:21:05.898 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [457] milliseconds
16-Sep-2023 11:21:05.905 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Tomcat-Standalone]
16-Sep-2023 11:21:05.905 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.76]
16-Sep-2023 11:21:06.072 WARNING [Catalina-utility-2] org.apache.tomcat.util.scan.StandardJarScanner.processURLs Failed to scan [file:/opt/confluence/lib/mysql-connector-java-8.0.33.jar] from classloader hierarchy
        java.io.IOException: java.lang.reflect.InvocationTargetException
                at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:209)
                at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:65)
                at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:49)
                at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:383)
                at org.apache.tomcat.util.scan.StandardJarScanner.processURLs(StandardJarScanner.java:318)
                at org.apache.tomcat.util.scan.StandardJarScanner.doScanClassPath(StandardJarScanner.java:270)
                at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:233)
                at org.apache.catalina.startup.ContextConfig.processJarsForWebFragments(ContextConfig.java:2132)
                at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1290)
                at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:987)
                at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:304)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4852)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1328)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1318)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:829)
        Caused by: java.lang.reflect.InvocationTargetException
                at java.base/jdk.internal.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:206)
                ... 21 more
        Caused by: java.util.zip.ZipException: zip END header not found
                at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
                at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
                at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
                at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
                at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
                at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
                at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
                at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
                at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
                at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
                ... 25 more
16-Sep-2023 11:21:06.083 SEVERE [main] org.apache.catalina.core.ContainerBase.startInternal A child container failed during start
        java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@6f2b63a0]
                at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
                at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:873)
                at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:795)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1328)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1318)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
                at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
                at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
                at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:249)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:923)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
        Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@6f2b63a0]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:139)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:173)
                at org.apache.catalina.webresources.StandardRoot.startInternal(StandardRoot.java:725)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4607)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4740)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1328)
                at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1318)
                at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:829)
        Caused by: java.lang.IllegalArgumentException: java.io.IOException: java.lang.reflect.InvocationTargetException
                at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:141)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
                ... 14 more
        Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
                at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:209)
                at org.apache.tomcat.util.compat.JreCompat.jarFileNewInstance(JreCompat.java:257)
                at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:138)
                ... 15 more
        Caused by: java.lang.reflect.InvocationTargetException
                at java.base/jdk.internal.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
                at org.apache.tomcat.util.compat.Jre9Compat.jarFileNewInstance(Jre9Compat.java:206)
                ... 17 more
        Caused by: java.util.zip.ZipException: zip END header not found
                at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
                at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
                at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
                at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
                at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
                at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
                at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
                at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
                at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
                at java.base/java.util.jar.JarFile.<init>(JarFile.java:350)
                ... 21 more

**Comment by haxqer** [comment]
确实有问题，我把版本降级
感谢提醒

**Comment by haxqer** [comment]
https://github.com/haxqer/confluence/tree/v8
降级至 8.4.2(latest) 测试过，没有问题
7.19.14 (lts) 正在测试中

**Comment by haxqer** [comment]
7.19.14 (lts) 已经测试过，没有问题
https://github.com/haxqer/confluence

给你添麻烦了，很抱歉。
给我提了个醒，以后需要验证后再push

**Comment by haxqer** [comment]
8.5.2 已测试
