### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by afw8k** [haxqer/confluence#58]
Hello, I get this Error now for the secound time and Confluence is not working anymore. Lasttime i backed up the MySQL Database and deployed Confluence again and restored the MySQL Backup. 

This Error Message i get when i go the the Confluence URL: 

A system error has occurred — our apologies!

For immediate troubleshooting, consult our [knowledge base](https://confluence.atlassian.com/confkb) for a solution.

If you would like to receive support from Atlassian's support team, ask your [Confluence administrator](https://wiki.afw4k.ch/contactadministrators.action) to create a support issue on [Atlassian's support system](https://support.atlassian.com/) with the following information:

a description of your problem and what you were doing at the time it occurred
a copy of the error and system information found below
a copy of the application logs (if possible).
Your Confluence administrator can use the [support request form](https://wiki.afw4k.ch/admin/raisesupportrequest.action) to create a support ticket which will include this information.

We will respond as promptly as possible.
Thank you!

[Return to site homepage…](https://wiki.afw4k.ch/)

Cause
Exception ID: cd15fb42-f9e3-458d-81e4-6d7f70951d20

Referer URL
Unknown

This Logs i see in the Container: 
06-Apr-2024 22:43:02.108 INFO [http-nio-8090-exec-87] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03PL0x960xb50xddd_0x8c0xeb7pEIvvyO0x000x0e0x830x82Lb0xa70xa6+)'0xa80xfed0x1c ]. HTTP method names must be tokens
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
07-Apr-2024 09:21:09.412 INFO [http-nio-8090-exec-82] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x00{0x010x000x00w0x030x030x8b]m0x8d0x91=0x010x810xab0xadx0xdd0xc9&DA0x18n\20x870x970xcc`}0xa40x1f0x050x110xf00xe590x000x000x1a0xc0/0xc0+0xc00x110xc00x070xc00x130xc00x090xc00x140xc00x0a0x000x050x00/0x0050xc00x120x000x0a0x010x000x0040x000x050x000x050x010x000x000x000x000x000x0a0x000x080x000x060x000x170x000x180x000x190x000x0b0x000x020x010x000x000x0d0x000x100x000x0e0x040x010x040x030x020x010x020x030x040x010x050x010x060x010xff0x010x000x010x00...]. HTTP method names must be tokens
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
07-Apr-2024 15:17:06.537 INFO [http-nio-8090-exec-85] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in method name [MGLNDD_158.220.81.42_80900x0a...]. HTTP method names must be tokens
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:263)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by haxqer** [comment]
I guess that might be:
https://stackoverflow.com/questions/42218237/tomcat-java-lang-illegalargumentexception-invalid-character-found-in-method-na
