### ISSUE TITLE
8.9.8 doesn't work anymore

### ISSUE THREAD

**Issue by LeuciJP** [haxqer/confluence#82]
Hello,
it seems like 8.9.8 isn't working anymore, as I got the following error:

I tried the old and new version, the docker container itself I havent tried to use,

<details><summary>Details</summary>
<p>

```
20:46:58 [Catalina-utility-2] o.a.c.c.C.[.[.[/synchrony-proxy][INFO] log - Initializing Spring DispatcherServlet 'dispatcher'
2024-12-07 20:46:59,457 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Starting Confluence 8.9.8 [build 9104 based on commit hash 5011e1c87a051acd841603998e673aad792f7afc] - synchrony version 6.0.7
2024-12-07 20:46:59,468 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM Eclipse Adoptium 17.0.11
2024-12-07 20:46:59,468 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.lang=ALL-UNNAMED
2024-12-07 20:46:59,468 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.io=ALL-UNNAMED
2024-12-07 20:46:59,469 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.util=ALL-UNNAMED
2024-12-07 20:46:59,469 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
2024-12-07 20:46:59,469 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
2024-12-07 20:46:59,469 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Djava.util.logging.config.file=/opt/atlassian/confluence/conf/logging.properties
2024-12-07 20:46:59,470 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
2024-12-07 20:46:59,470 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -javaagent:/opt/atlassian/agent/atlassian-agent-jar-with-dependencies.jar
2024-12-07 20:46:59,470 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Djdk.tls.ephemeralDHKeySize=2048
2024-12-07 20:46:59,470 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
2024-12-07 20:46:59,470 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
2024-12-07 20:46:59,471 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Datlassian.plugins.startup.options=
2024-12-07 20:46:59,471 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Dorg.apache.tomcat.websocket.DEFAULT_BUFFER_SIZE=32768
2024-12-07 20:46:59,471 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Dconfluence.context.path=
2024-12-07 20:46:59,471 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Dsynchrony.enable.xhr.fallback=true
2024-12-07 20:46:59,471 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Datlassian.plugins.enable.wait=300
2024-12-07 20:46:59,472 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Djava.awt.headless=true
2024-12-07 20:46:59,472 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Xlog:gc*:file=/opt/atlassian/confluence/logs/gc-%t.log:tags,time,uptime,level:filecount=5,filesize=2M
2024-12-07 20:46:59,472 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -XX:G1ReservePercent=20
2024-12-07 20:46:59,472 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -XX:+UseG1GC
2024-12-07 20:46:59,472 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -XX:+ExplicitGCInvokesConcurrent
2024-12-07 20:46:59,473 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -XX:+IgnoreUnrecognizedVMOptions
2024-12-07 20:46:59,473 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.lang=ALL-UNNAMED
2024-12-07 20:46:59,473 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
2024-12-07 20:46:59,473 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.net=ALL-UNNAMED
2024-12-07 20:46:59,473 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.io=ALL-UNNAMED
2024-12-07 20:46:59,474 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.nio=ALL-UNNAMED
2024-12-07 20:46:59,474 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.util=ALL-UNNAMED
2024-12-07 20:46:59,474 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
2024-12-07 20:46:59,474 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED
2024-12-07 20:46:59,475 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/sun.net.www.protocol.jar=ALL-UNNAMED
2024-12-07 20:46:59,475 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/sun.net.www.protocol.http=ALL-UNNAMED
2024-12-07 20:46:59,475 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/sun.net.www.protocol.https=ALL-UNNAMED
2024-12-07 20:46:59,475 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/sun.util.locale=ALL-UNNAMED
2024-12-07 20:46:59,475 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
2024-12-07 20:46:59,475 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.management/javax.management=ALL-UNNAMED
2024-12-07 20:46:59,476 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=java.management/sun.management=ALL-UNNAMED
2024-12-07 20:46:59,476 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED
2024-12-07 20:46:59,476 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-exports=java.base/sun.security.action=ALL-UNNAMED
2024-12-07 20:46:59,476 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-exports=java.base/sun.util.calendar=ALL-UNNAMED
2024-12-07 20:46:59,476 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED
2024-12-07 20:46:59,477 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-exports=java.xml/com.sun.org.apache.xml.internal.utils=ALL-UNNAMED
2024-12-07 20:46:59,477 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-exports=java.desktop/sun.font=ALL-UNNAMED
2024-12-07 20:46:59,477 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-exports=java.base/sun.security.util=ALL-UNNAMED
2024-12-07 20:46:59,477 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED
2024-12-07 20:46:59,478 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument --add-modules=java.se
2024-12-07 20:46:59,478 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -XX:ReservedCodeCacheSize=256m
2024-12-07 20:46:59,478 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Xms1024m
2024-12-07 20:46:59,478 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Xmx1024m
2024-12-07 20:46:59,478 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -javaagent:/home/atlassian-agent-jar-with-dependencies.jar
2024-12-07 20:46:59,478 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Dignore.endorsed.dirs=
2024-12-07 20:46:59,479 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Dcatalina.base=/opt/atlassian/confluence
2024-12-07 20:46:59,479 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Dcatalina.home=/opt/atlassian/confluence
2024-12-07 20:46:59,479 INFO [Catalina-utility-1] [com.atlassian.confluence.lifecycle] contextInitialized Using JVM argument -Djava.io.tmpdir=/opt/atlassian/confluence/temp
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "binDir" is null
	at io.zhile.crack.atlassian.agent.KeyTransformer.handleLicenseDecoder(KeyTransformer.java:84)
	at io.zhile.crack.atlassian.agent.KeyTransformer.transform(KeyTransformer.java:32)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2287)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:797)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1272)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1120)
	at com.atlassian.confluence.license.LicenseManagerFactoryBean.getObject(LicenseManagerFactoryBean.java:28)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1899)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1284)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:268)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:209)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1616)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1573)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:781)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:532)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:209)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
	at com.atlassian.confluence.setup.ConfluenceConfigurationListener.initialiseBootstrapContext(ConfluenceConfigurationListener.java:151)
	at com.atlassian.confluence.setup.ConfluenceConfigurationListener.contextInitialized(ConfluenceConfigurationListener.java:72)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4003)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4446)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
java.lang.NullPointerException: Cannot invoke "String.replace(java.lang.CharSequence, java.lang.CharSequence)" because "binDir" is null
	at io.zhile.crack.atlassian.agent.KeyTransformer.handleLicenseDecoder(KeyTransformer.java:84)
	at io.zhile.crack.atlassian.agent.KeyTransformer.transform(KeyTransformer.java:32)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2287)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:797)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1272)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1120)
	at com.atlassian.confluence.license.LicenseManagerFactoryBean.getObject(LicenseManagerFactoryBean.java:28)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1899)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1284)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:268)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:209)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1616)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1573)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:781)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:532)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:209)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
	at com.atlassian.confluence.setup.ConfluenceConfigurationListener.initialiseBootstrapContext(ConfluenceConfigurationListener.java:151)
	at com.atlassian.confluence.setup.ConfluenceConfigurationListener.contextInitialized(ConfluenceConfigurationListener.java:72)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4003)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4446)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
2024-12-07 20:47:02,830 WARN [Catalina-utility-1] [atlassian.config.util.BootstrapUtils] getBootstrapManager Attempting to retrieve bootstrap manager before it is set up: com.atlassian.confluence.util.VelocityUtil.isSetupComplete(VelocityUtil.java:796)
2024-12-07 20:47:02,895 WARN [Catalina-utility-1] [atlassian.config.util.BootstrapUtils] getBootstrapManager Attempting to retrieve bootstrap manager before it is set up: com.atlassian.confluence.util.VelocityUtil.isSetupComplete(VelocityUtil.java:796)
2024-12-07 20:47:02,958 WARN [Catalina-utility-1] [atlassian.config.util.BootstrapUtils] getBootstrapManager Attempting to retrieve bootstrap manager before it is set up: com.atlassian.confluence.util.VelocityUtil.isSetupComplete(VelocityUtil.java:796)
2024-12-07 20:47:02,972 WARN [Catalina-utility-1] [atlassian.config.util.BootstrapUtils] getBootstrapManager Attempting to retrieve bootstrap manager before it is set up: com.atlassian.confluence.util.VelocityUtil.isSetupComplete(VelocityUtil.java:796)
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
============================== agent working ==============================
```

</p>
</details> 

Any ideas how to fix it?

**Comment by voarsh2** [comment]
Logs aren't super helpful, and issue not very detailed

> I tried the old and new version, the docker container itself I havent tried to use,

This log is from a separate/test container?

**Comment by LeuciJP** [comment]
Wasn't able to respond faster, the issue was just on my side, thx anyways!
